# Generated by Django 4.1.5 on 2023-01-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_menucategories_delete_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuCategories',
            new_name='MenuCategory',
        ),
    ]
