# Generated by Django 4.1.5 on 2023-01-20 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category_price',
            field=models.TextField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='category_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.menu'),
        ),
    ]
