# Generated by Django 4.1.5 on 2023-01-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_menu_alter_menucategory_category_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contacts.menu'),
        ),
    ]
