# Generated by Django 4.1.5 on 2023-01-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_menuname'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_quant', models.IntegerField()),
                ('price_price', models.TextField(max_length=50)),
                ('price_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.menuname')),
            ],
        ),
    ]
