# Generated by Django 4.1.5 on 2023-01-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_date', models.DateTimeField(auto_now_add=True)),
                ('contacts_name', models.CharField(max_length=50)),
                ('contacts_email', models.EmailField(max_length=254)),
                ('contacts_text', models.TextField()),
            ],
        ),
    ]
