# Generated by Django 4.1.5 on 2023-01-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contacts_options_alter_contacts_contacts_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contacts_called',
            field=models.BooleanField(default=False),
        ),
    ]
