# Generated by Django 4.1.5 on 2023-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_contacts_called'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('contacts_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('contacts_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contacts_text', models.TextField()),
                ('contacts_called', models.BooleanField(default=False, verbose_name='Звонок')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['contacts_date'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
