# Generated by Django 4.1.5 on 2023-01-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_rename_category_type_menucategory_category_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='category_menu',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
