# Generated by Django 4.1.5 on 2023-01-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_menucategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'verbose_name': 'Категория меню', 'verbose_name_plural': 'Категории меню'},
        ),
    ]
