# Generated by Django 4.1.5 on 2023-01-20 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_menunames_alter_menucategory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuNames',
        ),
    ]
