# Generated by Django 4.1.5 on 2023-01-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_delete_menunames'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.menucategory')),
            ],
        ),
    ]
